# Generated by Django 4.0.1 on 2022-01-07 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english', models.CharField(max_length=200)),
                ('russian', models.CharField(max_length=200)),
                ('new_card', models.BooleanField(null=True)),
                ('remembered', models.BooleanField()),
                ('part_of_speech', models.CharField(max_length=200)),
                ('repeat', models.BooleanField()),
            ],
        ),
    ]
